CREATE TABLE mindfull_entries (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created TEXT NOT NULL,
    month_created TEXT NOT NULL,
    mood TEXT NOT NULL,
    stress_level INTEGER NOT NULL,
    gratitude1 TEXT NOT NULL,
    gratitude2 TEXT NOT NULL,
    gratitude3 TEXT NOT NULL,
    notes TEXT NOT NULL,
    userid INTEGER 
        REFERENCES mindfull_users(id) ON DELETE CASCADE NOT NULL
);